feature: test pre commit to changed files

diff --git a/tools/scripts/pre-commit b/tools/scripts/pre-commit
--- a/tools/scripts/pre-commit
+++ b/tools/scripts/pre-commit
@@ -1,35 +1,6 @@
 #!/usr/bin/env bash
 
 echo "
-===============
-|  Running detekt...
-===============
-"
-
-echo "Running detekt check..."
-fileArray=($@)
-detektInput=$(IFS=,;printf  "%s" "${fileArray[*]}")
-echo "Input files: $detektInput"
-
-./gradlew --no-daemon --stacktrace -PdisablePreDex detekt --input "$detektInput" 2>&1
-
-#detektStatus=$?
-
-# return 1 exit code if running checks fails
-#[ $detektStatus -ne 0 ] && exit 1
-
-#OUTPUT=$(detekt --input "$detektInput" 2>&1)
-EXIT_CODE=$?
-if [ $EXIT_CODE -ne 0 ]; then
-  echo $OUTPUT
-  echo "***********************************************"
-  echo "                 detekt failed                 "
-  echo " Please fix the above issues before committing "
-  echo "***********************************************"
-  exit $EXIT_CODE
-fi
-
-echo "
 ===================
 |  Mapping kotlin changed files...
 ===================
@@ -43,6 +14,18 @@ else
   echo "Changed files:"
   echo "$CHANGED_FILES"
 fi;
+
+echo "
+===============
+|  Running detekt...
+===============
+"
+./gradlew --no-daemon --stacktrace -PdisablePreDex detekt
+
+detektStatus=$?
+
+# return 1 exit code if running checks fails
+[ $detektStatus -ne 0 ] && exit 1
 
 echo "
 ===================
